# This is a basic workflow that is manually triggered

name: Tests
on:
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test
